<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>FishSocialOverlay</RootNamespace>
    <AssemblyName>FishSocialOverlay</AssemblyName>
    <StartupObject>FishSocialOverlay.App</StartupObject>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <None Include="OverlayResources\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
